sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Dk6g0Is5sQKCoACfnoyROXwu8LhjodIVgfxtgcCyXUOlb5wTjeEeq9OKbRdjsm54AqDo5+kcCUe67nA7rpvxVVCdRBoS14hYm15/OKcBBOAJo2HRr4hPn/Xq+LriTQmMUvT2TKhlVc8IP53ehA+gpKLrtY7Yrc+UVTAm6ozARg08zHr95U7jmWchXWHaMc3iivrGeIPgpvm4ovcWKCCZCIB9ZTT2cfs3W0/P4m7JLkTp6Lc1RhAY0bujyXiC1b0tWRMJqejR5A2kl5y11nwAAZZjkN/PMjwNFnDfmUfzfvPWDFVNbueuC8KS3ZV8rX83gFF8uvgzwSYVgXQY2kr6WNDSLLrySyvWCu2+jeVeHZN9mb6lJa585q2TDsHJWOV91vpU7qojFlwthrKe+yGorfUO8g3s9Qr5aKVRW8nFMDVq+5L9RcJegkFWP+gUT9iiWpcKoQlIAsQDSyptEkI/Dhd9WfEF1bwCU0p4s1NHY+/LMUdThmt9buL0XSl+ei2tYSen5yFkREurq7ap2ZCrsKC7GnzBujaoK6jveuJi3MHHwXSb5fWySU1OsSMpXeJEQo+JMT4MbxCJAeNXg974Pkz2bwIOXK43xYzwPF9zY7QJvUiMR/v+ulh2KwQ8uGsWsFEVh5DQBUzbJ/M5R8I+f/U3IQV1fCtwJeBVJo0Uvh0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/What-s-Mine-s-Mine---Volume-1_5966
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy